# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Global Configuration
exclude:
  - devnotes
  - LICENSE-theme
# the following are defaults
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
timezone: Europe/Moscow

# Build Command Options
strict_front_matter: true
baseurl: "/resume"

# Serve Command Options
port: 4004

# Sass/SCSS Options
sass:
  style: compressed

# WEBrick Options
#webrick:
#  headers:
#    Content-Security-Policy:

# Other Options
title: Сыропятов Вячеслав Владимирович
email: syrslava@yandex.ru
description: >-
  Резюме, Сыропятов Вячеслав Владимирович
url: "https://asrelo.github.io"
yandex_metrika_enabled: true
collections:
  posts:
    output: false
#plugins:
#  - jekyll-feed
